# Generated by Django 4.2.6 on 2023-11-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled',
            name='meal',
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='day',
            field=models.DateField(),
        ),
    ]
