# Generated by Django 4.2.6 on 2023-11-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userpersonalinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='calories',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
