# Generated by Django 4.2.6 on 2023-11-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_scheduled_meal_alter_scheduled_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled',
            old_name='day',
            new_name='date',
        ),
    ]
