# Generated by Django 4.2.6 on 2023-11-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_savedrecipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalrecipe',
            name='steps',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='steps',
            field=models.JSONField(),
        ),
    ]
