# Generated by Django 4.2.6 on 2023-11-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_globalrecipe_steps_alter_savedrecipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_img/'),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_img/'),
        ),
    ]
