# Generated by Django 4.2.6 on 2023-11-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_globalrecipe_image_savedrecipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
